config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :task_edit
  patch "tasks/:id", to: "tasks#update"

  delete 'tasks/:id', to: 'tasks#delete'
  get 'tasks/:id', to: 'tasks#show', as: :task


  # patch 'tasks/:id', to: 'tasks#show', as: :task


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to tasks_path
  end

  def delete
    @task = Task.find(params[:id])
    @task.delete
    redirect_to tasks_path
  end

  private
    def task_params
      params.require(:task).permit(:title, :details, :completed)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/fork-awesome@1.1.0/css/fork-awesome.min.css" integrity="sha256-sX8HLspqYoXVPetzJRE4wPhIhDBu2NB0kYpufzkQSms=" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h2>Edit</h2>

<%= form_for(@task) do |f| %>
<div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h2>My tasks</h2>
<% @tasks.each do |task| %>
  <%  if task.completed == true %>
   <p> <i class="fa fa-check-square-o" aria-hidden="true"></i>
      <%= link_to task.title, task_path(task[:id]) %> - <i class="fa fa-trash-o" aria-hidden="true"></i></p>
  <% else %>
   <p><i class="fa fa-square-o" aria-hidden="true"></i>
    <%= link_to task.title, task_path(task[:id]) %> - <i class="fa fa-trash-o" aria-hidden="true"></i></p>

  <% end %>
<% end %>


<%= link_to "Create New Task", tasks_new_path %>

app/views/tasks/new.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= f.label :completed %>
    <%= f.text_field :completed, class: 'form-control' %>
  </div>


  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>

<ul>
  <li><%= @task.details %></li>
</ul>

<!-- <form>
  <input type="button" value="Edit">
  <% button_to "Edit", task_edit_path(@task[:id]) %>
</form> -->

 <%= link_to "Edit Task", task_edit_path %>